import type { Metadata } from "next";
import { Footer, Header } from "@/components";
import { QueryProvider } from "@/providers";

export const metadata: Metadata = {
    title: "Cyber Shop",
    description: "Generated by create next app",
};

export default function HomeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            <QueryProvider>
                <Header />
                {children}
                <Footer />
            </QueryProvider>
        </main>
    );
}
