import type { Metadata } from "next";
import { BreadcrumbLinks, Footer, Header } from "@/components";

export const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-col min-h-screen">
      <Header />
      <div className="">
        <BreadcrumbLinks />
        {children}
      </div>
      <Footer />
    </main>
  );
}
