import { Footer, Header } from "@/components";
import Road from "@/components/Payment/Road";
import { QueryProvider } from "@/providers";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cyner Shop Profile",
  description: "Generated by create next app",
};

export default function PaymentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-col min-h-screen ">
      <QueryProvider>
        <Header isValidProfileIcon isValidCartIcon={false} />
        <Road />
        {children}
        <Footer />
      </QueryProvider>
    </main>
  );
}
